repos:
  - hooks:
      - id: ruff
        name: ruff-lint
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2

  - hooks:
      - id: ruff-format
        name: ruff-format
        args: [--check]
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2

  - hooks:
      - id: mypy
        name: mypy
        args: [--strict]
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
