name: Publish Package

on:
  # release:
  #   types: [created]
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Publish library"
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v4
        id: install-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: yezz123/setup-uv@v4
        id: install-uv

      - name: Build package
        run: |
          VERSION=$(uvx dunamai from any --no-metadata --style pep440).$(date +"%Y%m%d")
          echo $VERSION
          sed -i'' -E "s/version = \"0.0.0\"/version = \"$VERSION\"/g" pyproject.toml
          uvx --from build pyproject-build --installer uv

      # - name: Release to PyPI
      #   run: |
      #     uvx twine upload dist/* --non-interactive \
      #     --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}